version: '3'
services:
  miniconda:
    platform: linux/x86_64
    build: .
    image: takyam15/my-stats-python-r-jupyter:latest
    container_name: jupyterlab
    command: jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''
    ports:
     - "8888:8888"
    volumes:
     - ./Python:/work/Python
     - ./R:/work/R
    tty: true
    stdin_open: true
